/**
 * generateReportPdf — generates a comprehensive security assessment PDF report.
 *
 * @param {object} params
 * @param {string} params.assessmentId     Firestore document ID of the assessment
 * @param {object} [params.customizations] Optional customisation overrides
 * @returns {{ data: ArrayBuffer }}  PDF as an ArrayBuffer suitable for Blob creation
 */
import { jsPDF } from 'jspdf';
import { Assessment } from '@/entities/Assessment';

// ── Colour palette ────────────────────────────────────────────────────────────
const C = {
  bg:       [15,  23,  42],   // slate-900
  bg2:      [30,  41,  59],   // slate-800
  bg3:      [51,  65,  85],   // slate-700
  cyan:     [6,   182, 212],  // cyan-500
  purple:   [139, 92,  246],  // purple-500
  green:    [34,  197, 94],   // green-500
  red:      [239, 68,  68],   // red-500
  orange:   [249, 115, 22],   // orange-500
  yellow:   [234, 179, 8],    // yellow-500
  white:    [255, 255, 255],
  gray400:  [148, 163, 184],
  gray300:  [203, 213, 225],
};

function setFill(doc, rgb)   { doc.setFillColor(rgb[0], rgb[1], rgb[2]); }
function setTextRgb(doc, rgb) { doc.setTextColor(rgb[0], rgb[1], rgb[2]); }

function addPageBackground(doc, pageW, pageH) {
  setFill(doc, C.bg);
  doc.rect(0, 0, pageW, pageH, 'F');
}

function addHeader(doc, pageW, pageNum) {
  setFill(doc, C.bg2);
  doc.rect(0, 0, pageW, 20, 'F');
  setTextRgb(doc, C.cyan);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Hubcys Security Assessment Report', 14, 13);
  setTextRgb(doc, C.gray400);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${pageNum}`, pageW - 14, 13, { align: 'right' });
}

function addFooter(doc, pageW, pageH) {
  const now = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' });
  setTextRgb(doc, C.gray400);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by Hubcys — ${now} — Confidential`, pageW / 2, pageH - 6, { align: 'center' });
}

function checkPage(doc, y, pageH, pageW, pageNum) {
  if (y > pageH - 25) {
    doc.addPage();
    addPageBackground(doc, pageW, pageH);
    pageNum++;
    addHeader(doc, pageW, pageNum);
    addFooter(doc, pageW, pageH);
    return { y: 30, pageNum };
  }
  return { y, pageNum };
}

function addSectionTitle(doc, title, y, margin, pageW) {
  setFill(doc, C.bg2);
  doc.rect(margin, y - 5, pageW - margin * 2, 10, 'F');
  setFill(doc, C.purple);
  doc.rect(margin, y - 5, 3, 10, 'F');
  setTextRgb(doc, C.purple);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin + 6, y + 2);
  return y + 14;
}

function addKVRow(doc, label, value, y, margin, pageW) {
  setTextRgb(doc, C.gray400);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(label + ':', margin, y);
  setTextRgb(doc, C.white);
  doc.setFont('helvetica', 'bold');
  doc.text(String(value ?? '—'), margin + 55, y);
  return y + 8;
}

function addScoreBar(doc, label, score, y, margin, pageW) {
  const barW = pageW - margin * 2 - 40;
  const pct   = Math.max(0, Math.min(100, score || 0));
  const fill  = pct >= 70 ? C.green : pct >= 40 ? C.yellow : C.red;

  setTextRgb(doc, C.gray300);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(label, margin, y);

  setFill(doc, C.bg3);
  doc.rect(margin + 35, y - 4, barW, 6, 'F');
  setFill(doc, fill);
  doc.rect(margin + 35, y - 4, barW * (pct / 100), 6, 'F');

  setTextRgb(doc, C.white);
  doc.setFont('helvetica', 'bold');
  doc.text(`${pct}%`, margin + 35 + barW + 2, y);
  return y + 10;
}

function wrapText(doc, text, x, y, maxW, lineH, pageW, pageH, margin, pageNum) {
  const lines = doc.splitTextToSize(String(text || '—'), maxW);
  for (const line of lines) {
    const r = checkPage(doc, y, pageH, pageW, pageNum);
    y = r.y; pageNum = r.pageNum;
    doc.text(line, x, y);
    y += lineH;
  }
  return { y, pageNum };
}

// ── Main generator ────────────────────────────────────────────────────────────

export const generateReportPdf = async ({ assessmentId, customizations = {} }) => {
  if (!assessmentId) throw new Error('generateReportPdf: assessmentId is required');

  const assessment = await Assessment.get(assessmentId);
  if (!assessment) throw new Error('Assessment not found');

  const doc     = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW   = doc.internal.pageSize.getWidth();
  const pageH   = doc.internal.pageSize.getHeight();
  const margin  = 14;
  let y         = 0;
  let pageNum   = 1;

  // ── Cover Page ────────────────────────────────────────────────────────────
  addPageBackground(doc, pageW, pageH);

  // Cover gradient bar
  setFill(doc, C.cyan);
  doc.rect(0, 0, pageW, 4, 'F');

  // Logo / title area
  setTextRgb(doc, C.cyan);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('Hubcys', 14, 45);

  setTextRgb(doc, C.white);
  doc.setFontSize(18);
  doc.text('Security Assessment Report', 14, 57);

  setTextRgb(doc, C.gray400);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(assessment.company_name || 'Organisation', 14, 67);

  const dateStr = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long' });
  doc.text(dateStr, 14, 74);

  // Score circle
  const score = Math.round(assessment.overall_score ?? 0);
  const scoreColor = score >= 70 ? C.green : score >= 40 ? C.yellow : C.red;
  setFill(doc, C.bg2);
  doc.circle(pageW - 35, 55, 22, 'F');
  setTextRgb(doc, scoreColor);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(`${score}%`, pageW - 35, 52, { align: 'center' });
  setTextRgb(doc, C.gray400);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Overall Score', pageW - 35, 60, { align: 'center' });
  doc.text(assessment.maturity_level || 'Beginner', pageW - 35, 67, { align: 'center' });

  // Divider
  setFill(doc, C.bg3);
  doc.rect(margin, 85, pageW - margin * 2, 0.5, 'F');

  // Company info table
  y = 95;
  const infoRows = [
    ['Company',  assessment.company_name  || '—'],
    ['Industry', assessment.industry_sector || '—'],
    ['Size',     assessment.company_size ? `${assessment.company_size} employees` : '—'],
    ['Date',     dateStr],
    ['Report ID', assessmentId.slice(0, 8).toUpperCase()],
  ];
  for (const [label, value] of infoRows) {
    y = addKVRow(doc, label, value, y, margin, pageW);
  }

  // Confidentiality notice
  y = pageH - 50;
  setFill(doc, C.bg2);
  doc.rect(margin, y, pageW - margin * 2, 30, 'F');
  setTextRgb(doc, C.yellow);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('CONFIDENTIAL', pageW / 2, y + 10, { align: 'center' });
  setTextRgb(doc, C.gray400);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'This report contains sensitive security information. Distribute only on a need-to-know basis.',
    pageW / 2, y + 18, { align: 'center' }
  );

  addFooter(doc, pageW, pageH);

  // ── Page 2: Executive Summary ──────────────────────────────────────────────
  doc.addPage();
  addPageBackground(doc, pageW, pageH);
  pageNum++;
  addHeader(doc, pageW, pageNum);
  addFooter(doc, pageW, pageH);

  y = 30;
  y = addSectionTitle(doc, 'Executive Summary', y, margin, pageW);
  y += 4;

  if (assessment.grand_summary) {
    // Render the grand summary (strip markdown formatting)
    const cleanSummary = assessment.grand_summary
      .replace(/##? /g, '')
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/^[-•] /gm, '• ');

    setTextRgb(doc, C.gray300);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const r = wrapText(doc, cleanSummary, margin, y, pageW - margin * 2, 5.5, pageW, pageH, margin, pageNum);
    y = r.y; pageNum = r.pageNum;
  } else {
    setTextRgb(doc, C.gray400);
    doc.setFontSize(9);
    doc.text('No executive summary available. Run AI Analysis to generate one.', margin, y);
    y += 10;
  }

  // ── Page 3: Domain Scores ──────────────────────────────────────────────────
  const p = checkPage(doc, y + 20, pageH, pageW, pageNum);
  y = p.y; pageNum = p.pageNum;

  y = addSectionTitle(doc, 'Security Domain Scores', y, margin, pageW);
  y += 4;

  const domains = [
    { label: 'Endpoint Security',       score: assessment.endpoint_security_score },
    { label: 'Data & Monitoring',        score: assessment.data_monitoring_score },
    { label: 'Identity & Access',        score: assessment.identity_access_score },
    { label: 'Governance & Compliance',  score: assessment.governance_score },
    { label: 'Incident Response',        score: assessment.incident_response_score },
    { label: 'Vulnerability Management', score: assessment.vulnerability_management_score },
    { label: 'Overall Score',            score: assessment.overall_score },
  ].filter(d => d.score !== undefined && d.score !== null);

  for (const d of domains) {
    const r = checkPage(doc, y, pageH, pageW, pageNum);
    y = r.y; pageNum = r.pageNum;
    y = addScoreBar(doc, d.label, d.score, y, margin, pageW);
  }

  // ── Key Findings ───────────────────────────────────────────────────────────
  const r2 = checkPage(doc, y + 20, pageH, pageW, pageNum);
  y = r2.y; pageNum = r2.pageNum;

  y = addSectionTitle(doc, 'Key Findings & Recommendations', y, margin, pageW);
  y += 4;

  setTextRgb(doc, C.gray300);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  const findings = assessment.key_findings || assessment.recommendations ||
    'This section is populated from the AI analysis results. Run Smart Analysis to generate findings.';

  const rWrap = wrapText(doc, findings, margin, y, pageW - margin * 2, 5.5, pageW, pageH, margin, pageNum);
  y = rWrap.y; pageNum = rWrap.pageNum;

  // ── Maturity Assessment ────────────────────────────────────────────────────
  const r3 = checkPage(doc, y + 20, pageH, pageW, pageNum);
  y = r3.y; pageNum = r3.pageNum;

  y = addSectionTitle(doc, 'Maturity Assessment', y, margin, pageW);
  y += 4;

  y = addKVRow(doc, 'Maturity Level',    assessment.maturity_level    || '—', y, margin, pageW);
  y = addKVRow(doc, 'Overall Score',     `${assessment.overall_score ?? 0}%`,  y, margin, pageW);
  y = addKVRow(doc, 'Industry',          assessment.industry_sector   || '—', y, margin, pageW);
  y = addKVRow(doc, 'Company Size',      assessment.company_size      || '—', y, margin, pageW);

  // ── Footer bar ──────────────────────────────────────────────────────────────
  return { data: doc.output('arraybuffer') };
};
