/**
 * generateNis2Report — generates a NIS2 Directive compliance reference PDF.
 *
 * @param {object} [params]
 * @returns {{ data: ArrayBuffer }}   PDF as ArrayBuffer for Blob creation
 */
import { jsPDF } from 'jspdf';

const C = {
  bg:      [15,  23,  42],
  bg2:     [30,  41,  59],
  bg3:     [51,  65,  85],
  blue:    [59,  130, 246],
  cyan:    [6,   182, 212],
  purple:  [139, 92,  246],
  yellow:  [234, 179, 8],
  white:   [255, 255, 255],
  gray400: [148, 163, 184],
  gray300: [203, 213, 225],
  green:   [34,  197, 94],
};

function rgb(doc, c)  { doc.setTextColor(c[0], c[1], c[2]); }
function fill(doc, c) { doc.setFillColor(c[0], c[1], c[2]); }
function addBg(doc, w, h) { fill(doc, C.bg); doc.rect(0, 0, w, h, 'F'); }

function addHeader(doc, w) {
  fill(doc, C.bg2);
  doc.rect(0, 0, w, 20, 'F');
  fill(doc, C.blue);
  doc.rect(0, 0, w, 2, 'F');
  rgb(doc, C.blue);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('NIS2 DIRECTIVE (EU 2022/2555) — Compliance Reference', 14, 8);
  rgb(doc, C.gray400);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Hubcys — Not Legal Advice', 14, 15);
}

function addFooter(doc, w, h) {
  const d = new Date().toLocaleString('en-GB');
  rgb(doc, C.gray400);
  doc.setFontSize(7);
  doc.text(`Generated ${d} — Hubcys — For Internal Use Only`, w / 2, h - 6, { align: 'center' });
}

function newPage(doc, w, h) {
  doc.addPage();
  addBg(doc, w, h);
  addHeader(doc, w);
  addFooter(doc, w, h);
  return 28;
}

function checkPage(doc, y, h, w) {
  if (y > h - 25) return newPage(doc, w, h);
  return y;
}

function section(doc, title, y, margin, w) {
  fill(doc, C.bg2);
  doc.rect(margin, y - 4, w - margin * 2, 9, 'F');
  fill(doc, C.blue);
  doc.rect(margin, y - 4, 3, 9, 'F');
  rgb(doc, C.blue);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin + 6, y + 2);
  return y + 13;
}

function bullet(doc, text, y, margin, maxW, w, h) {
  rgb(doc, C.gray300);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize('• ' + text, maxW - 4);
  for (const line of lines) {
    y = checkPage(doc, y, h, w);
    doc.text(line, margin + 3, y);
    y += 5.5;
  }
  return y;
}

export const generateNis2Report = async (params = {}) => {
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW  = doc.internal.pageSize.getWidth();
  const pageH  = doc.internal.pageSize.getHeight();
  const margin = 14;
  const maxW   = pageW - margin * 2;

  // ── Cover ──────────────────────────────────────────────────────────────────
  addBg(doc, pageW, pageH);
  fill(doc, C.blue);
  doc.rect(0, 0, pageW, 4, 'F');

  rgb(doc, C.blue);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('NIS2 DIRECTIVE', margin, 30);

  rgb(doc, C.white);
  doc.setFontSize(18);
  doc.text('EU 2022/2555 — Compliance Reference', margin, 42);

  rgb(doc, C.gray400);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 52);
  doc.text('Applies to Essential and Important Entities in the EU', margin, 60);

  addFooter(doc, pageW, pageH);

  // ── Page 2: Overview ──────────────────────────────────────────────────────
  let y = newPage(doc, pageW, pageH);

  y = section(doc, 'NIS2 Overview', y, margin, pageW);
  const overview = [
    'NIS2 (EU 2022/2555) replaces the original NIS Directive and significantly expands the scope of cybersecurity obligations across the EU.',
    'Applies to: Essential entities (energy, transport, banking, health, water, digital infrastructure) and Important entities (postal, waste, chemicals, food, manufacturing, digital providers).',
    'Member States must transpose NIS2 into national law by 17 October 2024.',
    'Penalties: Up to €10M or 2% of global turnover for Essential entities; €7M or 1.4% for Important entities.',
  ];

  rgb(doc, C.gray300);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  for (const line of overview) {
    y = checkPage(doc, y, pageH, pageW);
    const ls = doc.splitTextToSize(line, maxW);
    for (const l of ls) { doc.text(l, margin, y); y += 5.5; }
    y += 2;
  }

  // ── Article 21 Security Measures ──────────────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  y = section(doc, 'Article 21 — Security Measures', y, margin, pageW);

  const article21 = [
    'Risk analysis and information system security policies',
    'Incident handling (prevention, detection, and response)',
    'Business continuity and crisis management',
    'Supply chain security including relationships with suppliers and service providers',
    'Security in network and information systems acquisition, development, and maintenance',
    'Policies and procedures to assess effectiveness of cybersecurity risk management',
    'Basic cyber hygiene practices and cybersecurity training',
    'Policies and procedures regarding the use of cryptography and encryption',
    'Human resources security, access control policies, and asset management',
    'Use of multi-factor authentication or continuous authentication solutions',
  ];

  for (const item of article21) {
    y = bullet(doc, item, y, margin, maxW, pageW, pageH);
  }

  // ── Article 23 Incident Reporting ─────────────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  y = section(doc, 'Article 23 — Incident Reporting Obligations', y, margin, pageW);

  const reporting = [
    { label: 'Early Warning (24 hours)',    text: 'Notify the relevant CSIRT or competent authority within 24 hours of becoming aware of a significant incident.' },
    { label: 'Incident Notification (72 hours)', text: 'Provide an initial notification within 72 hours with: classification, preliminary assessment, severity, impact, and indicators of compromise (if available).' },
    { label: 'Intermediate Report',         text: 'Provide status updates upon request from the competent authority or CSIRT.' },
    { label: 'Final Report (1 month)',       text: 'Submit a final report within 1 month of incident notification including: detailed description, type of threat, root cause, applied and ongoing measures, and cross-border impact.' },
  ];

  for (const item of reporting) {
    y = checkPage(doc, y, pageH, pageW);
    rgb(doc, C.cyan);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.text(item.label + ':', margin + 3, y);
    y += 5.5;
    rgb(doc, C.gray300);
    doc.setFont('helvetica', 'normal');
    const ls = doc.splitTextToSize(item.text, maxW - 6);
    for (const l of ls) { doc.text(l, margin + 6, y); y += 5; }
    y += 3;
  }

  // ── Significant Incident Definition ────────────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  y = section(doc, 'Significant Incident Criteria', y, margin, pageW);

  const sigCriteria = [
    'Has caused or is capable of causing severe operational disruption or financial losses for the entity concerned',
    'Has affected or is capable of affecting other natural or legal persons by causing considerable material or non-material damage',
    'Affects services to more than a defined number of users (threshold set by Member States)',
    'Has caused or is capable of causing significant downtime lasting more than a defined threshold',
    'Cross-border impact affecting more than one Member State',
  ];

  for (const item of sigCriteria) {
    y = bullet(doc, item, y, margin, maxW, pageW, pageH);
  }

  // ── Governance & Management Accountability ──────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  y = section(doc, 'Article 20 — Governance & Management Accountability', y, margin, pageW);

  const governance = [
    'Management bodies of essential and important entities are responsible for approving the entity\'s cybersecurity risk management measures.',
    'Management bodies must follow cybersecurity training and encourage their entities to offer similar training to employees regularly.',
    'Management body members may be held personally liable for infringements of NIS2 obligations.',
  ];

  rgb(doc, C.gray300);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  for (const line of governance) {
    y = checkPage(doc, y, pageH, pageW);
    const ls = doc.splitTextToSize(line, maxW);
    for (const l of ls) { doc.text(l, margin, y); y += 5.5; }
    y += 3;
  }

  // ── Implementation Checklist ───────────────────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  y = section(doc, 'Implementation Checklist', y, margin, pageW);

  const checklist = [
    'Determine if your organisation is an Essential or Important Entity under NIS2 Annex I/II',
    'Register with the relevant national competent authority (by Oct 2024)',
    'Appoint a responsible person/team for cybersecurity governance',
    'Conduct a cybersecurity risk assessment aligned with Article 21',
    'Establish or update your incident response plan with NIS2 reporting timelines',
    'Implement multi-factor authentication across all critical systems',
    'Review and update supply chain security contracts and assessments',
    'Establish a business continuity plan with cybersecurity scenarios',
    'Deliver cybersecurity awareness training to all staff',
    'Test incident response procedures with tabletop exercises',
    'Implement logging and monitoring for all critical systems',
    'Establish a vulnerability disclosure and management process',
  ];

  for (const item of checklist) {
    y = checkPage(doc, y, pageH, pageW);
    rgb(doc, C.gray400);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.text('☐', margin, y);
    const ls = doc.splitTextToSize(item, maxW - 8);
    rgb(doc, C.gray300);
    for (const l of ls) { doc.text(l, margin + 7, y); y += 5.5; }
    y += 1;
  }

  // ── Disclaimer ────────────────────────────────────────────────────────────
  y = checkPage(doc, y + 10, pageH, pageW);
  fill(doc, C.bg2);
  doc.rect(margin, y, maxW, 20, 'F');
  rgb(doc, C.yellow);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('DISCLAIMER', margin + 4, y + 8);
  rgb(doc, C.gray400);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  const disclaimer = 'This document is for informational purposes only and does not constitute legal advice. Consult qualified legal counsel for compliance matters specific to your organisation.';
  const dls = doc.splitTextToSize(disclaimer, maxW - 8);
  let dy = y + 14;
  for (const l of dls) { doc.text(l, margin + 4, dy); dy += 5; }

  return { data: doc.output('arraybuffer') };
};
